packages:
  - server

onlyBuiltDependencies:
  - esbuild
  - leveldown
  - '@embedded-postgres/darwin-arm64'
  - '@embedded-postgres/darwin-x64'
  - '@embedded-postgres/linux-x64'
  - '@embedded-postgres/linux-arm64'
